SELECT COUNT(*) as FISH_COUNT, n.FISH_NAME as FISH_NAME 
from FISH_INFO i 
INNER JOIN FISH_NAME_INFO n ON i.FISH_TYPE = n.FISH_TYPE 
group by n.FISH_TYPE, n.FISH_NAME
order by FISH_COUNT desc;



# SELECT COUNT(*) as FISH_COUNT, FISH_NAME 
# FROM FISH_INFO LEFT OUTER JOIN FISH_NAME_INFO
# ON FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE 
# group by FISH_INFO.FISH_TYPE;
# ORDER BY FISH_COUNT ASC