SELECT 
    SUM(HG.SCORE) as SCORE, 
    HG.EMP_NO as EMP_NO, 
    HE.EMP_NAME as EMP_NAME, 
    HE.POSITION as POSITION,
    HE.EMAIL as EMAIL 
FROM HR_GRADE HG 
INNER JOIN HR_EMPLOYEES HE 
    ON HG.EMP_NO = HE.EMP_NO 
GROUP BY HG.EMP_NO 
ORDER BY SCORE DESC 
LIMIT 1;